#! /usr/bin/env python3

import clipboard
import json
import os 
import sys 

class clippyBo:

	def __init__(self):
		
		self.FILELOC = os.path.expanduser("~/Documents/CLIPPYBO.json")
		self.data = {}
		print("Welcome To ClippyBo")

	@staticmethod	
	def checkFile():
		FILELOC = os.path.expanduser("~/Documents/CLIPPYBO.json")
		if os.path.exists(FILELOC):
			pass
		else : 
			with open(FILELOC,"w") as file:
				pass

	def load(self):
		clippyBo.checkFile()
	
		print("Enter the key you want to copy\nYou can use the 'show' args to look for keys and data")

		key = input("Enter : ")
	
		with open(self.FILELOC,"r") as file:
			self.data = json.load(file)
			if (self.data[key]):
				paste_data = self.data[key]
				clipboard.copy(paste_data)
			else :
				print("No such data every stored")
	
	def save(self):	
		clippyBo.checkFile()
		with open(self.FILELOC,"r+") as file:
			try :
				self.data = json.load(file)
			except :
				self.data = {} 

		print("Enter the key for your clipboard data : ")
		key = input("Type in : ")

		paste_data = clipboard.paste()
		self.data[key] = paste_data
		
		with open(self.FILELOC,"w") as file:
			json.dump(self.data,file)

	def show(self):	
		clippyBo.checkFile()
		with open(self.FILELOC,"r") as file:
			self.data = json.load(file)

		for key in self.data:
			print(" -------------- ")
			print(key)
			print(self.data[key])
			print(" -------------- ")
			print()

clip = clippyBo()

if len(sys.argv) == 2:
	command = sys.argv[1]

	if command == "save":
		clip.save()

	elif command == "show":
		clip.show()

	elif command == "load":
		clip.load()
	else:
		print("Give a valid command")
